# Site settings
title: Haris Wang's Blog
email: 
description: "Always seek after truth."
baseurl: ""
url: "http://dynmi.github.io"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
